import type {ConceptPage} from './content';

export const workflowPages:ConceptPage[]=[
  {id:'quickstart',path:'/learn/quickstart',label:'Quickstart',title:'Your first memory',intro:'Save a source, retrieve it, and trace the result back to the original. One small loop that makes the rest of Scone concrete.',sections:[
    {id:'connect',title:'1. Connect a memory space',body:'Open your Scone workspace and use **Memory connection** to enter a space key from your server configuration. A space key belongs to Scone—not to your model provider. For the terminal example, set `SCONE_URL` to your server and `SCONE_KEY` to a key for a test space. Keep the key out of URLs and source control.'},
    {id:'source',title:'2. Save and retrieve a source',body:'Run this example in your own terminal. The first request stores a short note. The second searches the same authorized space. Nothing runs when you read or copy this page. Python returns a successful ingest receipt; Rust uses HTTP 201 for a new source. Both identify the stored episode.'},
    {id:'inspect',title:'3. Open the evidence',body:'Keep the returned `episode_id`. Read it with `GET /v1/episodes/{id}`, or open the corresponding source in **Documents**. Recall returns excerpts, not a model-written answer. Compare the excerpt with the retained original before building it into an agent prompt.'},
    {id:'next',title:'4. Add the next layer',body:'Configure consolidation to turn sources into claim proposals, use **Review** to decide what should enter claim recall, then explore stored relationships in the **Playground**. For a conversation, configure the conversation service separately; an authenticated memory connection alone does not start a reply or speech model.'},
  ],actions:[{label:'Open Documents',to:'/memory#documents'},{label:'Understand graph memory',to:'/learn/graph-memory'}]},
  {id:'sources',path:'/learn/sources',label:'Add sources',title:'Bring your knowledge into Scone',intro:'Sources are the material your memory is built from: notes, retained conversations, imported text, and original attachments.',sections:[
    {id:'source-record',title:'A source is a retained original',body:'Each stored episode has an identity, content, source metadata and timestamps. Retrieval chunks refer back to that episode. A filename or URL describes provenance; it does not replace the stored identity. Keep source IDs when your integration needs to inspect, update or forget records later.'},
    {id:'inputs',title:'Choose an ingestion path',body:'| Input | Where to begin |\n| --- | --- |\n| Notes and text | Documents → Add source, or `POST /v1/episodes` |\n| Text, Markdown and code files | Documents text import on supported Python hosts |\n| Original images | Authenticated attachment upload and episode linking on Python |\n| Agent interactions | Playground → Connect agents; configure and verify each host |\n| URLs, PDFs, audio and video | Check the native integration and format-specific support before importing |\n\nA saved image marker is not an uploaded image. Automatic OCR, transcription, connector synchronization and universal file parsing are not implied by the text-ingestion API.'},
    {id:'metadata',title:'Organize without moving the original',body:'Use tags for simple labels and metadata for values such as `project`, `status` or `priority`. Those fields narrow retrieval inside a space. They do not create permissions. Preserve literal values so filters can match the metadata actually stored.'},
    {id:'identity',title:'Understand duplicate receipts',body:'An ingest may return an existing episode instead of adding a duplicate. Inspect the receipt rather than assuming every request created a new record. Reusing a deduplication key is not a document-replacement API; it can resolve to the earlier content. Stable updates and resumable imports need their own verified contracts.'},
    {id:'progress',title:'Check what has finished',body:'Use Memory → Status to inspect source counts and, where `jobs.read` is supported, batch history. Search readiness and completed claim consolidation are different milestones. A failed batch record should be inspected before you retry an import.'},
  ],actions:[{label:'Add a source',to:'/memory#documents'},{label:'See processing status',to:'/memory#status'}]},
  {id:'search',path:'/learn/search',label:'Search & retrieval',title:'Retrieve the context you need',intro:'Search returns source passages and eligible claims. Narrow the candidates, inspect their evidence, and decide what belongs in the next interaction.',sections:[
    {id:'two-outputs',title:'Passages and claims serve different needs',body:'A passage is text retained from a source. A claim is a ledger statement with an origin, status and validity interval. Use passages to ground an answer in original material; use eligible claims to describe recorded state. Neither a retrieval score nor a graph position proves a statement is true.'},
    {id:'query',title:'Ask a focused question',body:'Use **Memory → Search** or `GET /v1/recall?q=...`. Results include source identities you can follow. Check degradation information when a retrieval lane fails. Ranking behavior depends on the configured stores and embedder; an offline hash fixture is not a semantic-quality benchmark.'},
    {id:'filters',title:'Narrow before the engine searches',body:'Where `recall.conditions` is supported, the metadata editor combines **all** and **any** groups with exact text, substring, list, numeric and presence tests. Editing is a draft; **Apply** runs the narrowed search. **Cancel** keeps the applied query, and **Clear** explicitly removes it.\n\nA missing metadata key never matches—even for a negated rule. Numeric comparisons parse stored text. Invalid filters are rejected, not ignored. Some stores cannot apply conditions directly; the engine checks candidates, but a widened candidate window can still leave a short result set.'},
    {id:'time',title:'Current and historical context',body:'Use an as-of boundary when asking about an earlier state. Validity time describes when a claim applies; ingestion time describes when Scone received it. Keep these dates distinct when importing older material or evaluating a correction.'},
    {id:'agent',title:'Put evidence into an agent’s context',body:'Your application decides how to incorporate returned context. A recorded recall proves retrieval occurred; it does not prove the model used every result or answered correctly. Inspect the original source and record explicit outcome feedback when available.'},
  ],actions:[{label:'Search memory',to:'/memory#search'},{label:'Explore recorded recall',to:'/playground'}]},
  {id:'review',path:'/learn/review',label:'Review & control',title:'Decide what your memory should keep',intro:'Review model-extracted proposals, understand their support, and control how recorded claims participate in future retrieval.',sections:[
    {id:'inbox',title:'Start with the review inbox',body:'Review groups proposals so a long-running capture session does not become one undifferentiated list. Filter the queue, read source quotations, and open the full original before approving or declining. A quotation check verifies that words occur in a source—not that their interpretation is correct.'},
    {id:'bulk',title:'Make a bounded batch decision',body:'Bulk approval freezes the matching set across pages. Inspect its confirmation: new arrivals are not silently included. Partial results and conflicts require follow-up rather than a blanket success message. The server’s permissions decide whether a key can approve; the UI cannot grant that authority.'},
    {id:'ledger',title:'A ledger record is not a review receipt',body:'An active claim may come from a direct authorized assertion rather than a human review. Keep **origin**, **record status**, **source grounding** and **approval history** separate. A proposed inference is not automatically approved because its premises were accepted.'},
    {id:'control',title:'Close, exclude or forget deliberately',body:'Closing a claim ends its validity. Excluding controls its retrieval where supported. Forgetting a source affects retained material and must be understood through that host’s impact and completion receipts. None of these should be described as universal erasure without verifying dependent records, indexes and retained events.'},
  ],actions:[{label:'Open Review',to:'/memory#review'},{label:'Inspect Memory claims',to:'/memory#beliefs'}]},
  {id:'profiles',path:'/learn/profiles',label:'Profiles',title:'Context that carries between interactions',intro:'A profile offers a compact selection of recorded knowledge and recent source context for an agent or a person.',sections:[
    {id:'profile',title:'A view over memory, not another source',body:'Profiles assemble context from the space’s eligible records. They should not create a second, untraceable truth store. Inspect a profile item’s source or supporting claim when you need to understand why it is present.'},
    {id:'read',title:'Read the current profile',body:'Open **Memory → Profile** when `profile.read` is advertised, or use `GET /v1/profile` with the space key. Native response shapes and selection policies can differ. The workspace validates the response instead of filling missing fields with fabricated context.'},
    {id:'changes',title:'Keep the profile connected to its evidence',body:'A claim closing or a source being forgotten can change which context remains eligible. Refresh to inspect the current server response. A cached summary should not be presented as freshly verified memory after its evidence changes.'},
    {id:'usage',title:'Use profiles alongside focused recall',body:'A profile supplies broad continuity; a query supplies task-specific context. Combine them according to your application’s context budget. Repeated appearances are not calibrated confidence, and a short summary cannot replace the source when precision matters.'},
  ],actions:[{label:'Open Profile',to:'/memory#profile'},{label:'Try focused recall',to:'/memory#search'}]},
  {id:'conversations',path:'/learn/conversations',label:'Conversations & voice',title:'Conversations that remember',intro:'Connect Scone’s memory to a configured conversation runtime, with independent choices for replies, transcription, speech and activity detection.',sections:[
    {id:'services',title:'Memory and conversation are separate services',body:'A working memory API does not mean a reply model or audio transport is configured. Open **Conversations** to see the service’s actual readiness. The recorded local memory-only launcher does not enable conversations or voice by itself.'},
    {id:'text',title:'Run a text conversation',body:'On a configured host, create a session, send a turn, and inspect its completion receipt. Saved public messages have source identities. Reopening a transcript does not reconstruct missing per-turn context receipts, and a completed response is not relabeled as a token stream.'},
    {id:'persona',title:'Choose a coherent persona',body:'A persona binds instructions to independent **reply**, **transcription**, **speech**, and optional **activity detection** selections. The operator configures the provider registry and credentials; the client selects among advertised options. A speech provider is not a language model, and an orchestration framework is not a voice.'},
    {id:'voice',title:'Connect browser audio intentionally',body:'The voice control requires a ready service and explicit microphone permission. Browser input, server transport and audio output can fail independently. Follow the stage-specific recovery message. Stopping releases local media; failed connections do not automatically reattach. Provider and real-device validation are separate from synthetic browser tests.'},
    {id:'capture',title:'Understand what is recorded',body:'Only public interactions and supported capture events are retained. No hidden reasoning is captured. Missing events remain missing. A context receipt shows what was prepared or retrieved, not proof that a model used it correctly. Stored audio/video replay and broader transports require their own supported workflows.'},
  ],actions:[{label:'Open Conversations',to:'/conversations'},{label:'Connect agent capture',to:'/playground'}]},
  {id:'spaces',path:'/learn/spaces',label:'Spaces & keys',title:'Keep each memory in its own space',intro:'A space is an access boundary. Metadata organizes content within it; credentials decide who can reach it.',sections:[
    {id:'keys',title:'Use a Scone key',body:'Send `Authorization: Bearer <your-space-key>` to your own Scone server. The local host’s configuration or administrator supplies the key. It is not an OpenAI, Claude or speech-provider credential. The webapp keeps it in page memory, not browser storage.'},
    {id:'isolation',title:'Narrowing does not grant access',body:'Tags, scope metadata and search conditions select records inside the authenticated space. Changing a filter does not grant access to another user’s data. Inspect the connected space before importing, reviewing or forgetting material.'},
    {id:'roles',title:'Use only the permissions you need',body:'Native key roles distinguish reading, writing, review and full access where configured. A read-only inspection must not become a mutation. A permission denial does not necessarily invalidate the key; an expired or unknown key requires reconnecting.'},
    {id:'operations',title:'Operate your own host deliberately',body:'Bind local development to loopback. Configure persistence, backups, model services and exposed network access explicitly. Starting a server is not proof that its consolidation model, agent capture or voice service is healthy. Use status and real workflow receipts to verify each layer.'},
  ],actions:[{label:'Open workspace status',to:'/memory#status'},{label:'Read the API map',to:'/learn/api'}]},
  {id:'api',path:'/learn/api',label:'API reference',title:'The Scone API, by workflow',intro:'A practical map of the native HTTP surface. Check capability discovery before enabling an optional operation.',sections:[
    {id:'discovery',title:'Discover the connected host',body:'`GET /v1/capabilities` reports a versioned manifest. `GET /v1/status` identifies the space and available status fields. Authenticate both requests. Missing optional capabilities are not invitations to guess an endpoint or show a working control.'},
    {id:'memory',title:'Store, read and retrieve',body:'| Method | Path | Purpose |\n| --- | --- | --- |\n| POST | `/v1/episodes` | Retain source content and return its identity |\n| GET | `/v1/episodes/{id}` | Inspect one authorized source |\n| GET | `/v1/sources` | Page source inventory on supported hosts |\n| GET | `/v1/recall` | Retrieve passages and eligible claim context |\n| GET | `/v1/profile` | Read the host’s profile for this space |\n| GET | `/v1/graph` | Inspect recorded nodes and relationships |'},
    {id:'decisions',title:'Inspect and decide claims',body:'`GET /v1/facts` reads ledger records. Supported hosts expose approval, decline and close operations for identified claims. Python’s `facts.links` surface exposes typed relationships and named source support. Exclusion, inclusion, bulk decisions and source governance require their own permissions and contracts.'},
    {id:'runtime',title:'Optional services',body:'Batch history, processing controls, conversations, public streaming and voice are separate surfaces—not implied by a healthy memory API. Use the corresponding advertised capability and documented request/receipt shape. Rust remains a first-class engine host and CLI; Python owns the broader conversation service.'},
    {id:'errors',title:'Handle failures by their meaning',body:'| Response | Next action |\n| --- | --- |\n| 400 / 422 | Correct the input; invalid conditions are not ignored |\n| 401 | Connect with an accepted Scone key |\n| 403 | Use an authorized role; do not repeat a denied write |\n| 404 / 410 | Treat the source as unavailable or forgotten according to the receipt |\n| 429 / 503 | Respect reported backpressure and retry guidance |\n\nA timed-out write is not proof that nothing was saved. Inspect its receipt or retained identity before repeating it. Error responses can differ between native hosts; use their machine-readable contract rather than matching prose.'},
  ],actions:[{label:'Run the quickstart',to:'/learn/quickstart'},{label:'Inspect host capabilities',to:'/memory#status'}]},
];
